### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by cigarsam** [Na-He/Fast-NR#1]
Hi - I receive the following error when running Fast-NR. Could you recommend some actions for troubleshooting. Thanks!
Fast-NR -t x.bam -c y.bam -g hg19.chrom.sizes -o 285vs288_FAST_NR.txt -p 1.00e-05 -ws 600 -cp Bonferroni -cm Cosine -ct 2.50e-01 -l 0 -rm False.
Step 1: Read in input files.
Read in chromosome size file.
Read in control file.
Traceback (most recent call last):
  File "/usr/local/bin/Fast-NR", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/src/FastNR.py", line 42, in main
    control=controlPro.Genome_Frag_all_pos(chrSizeList)
  File "/usr/local/lib/python2.7/site-packages/src/FastNR.py", line 363, in Genome_Frag_all_pos
    if not read1 is None and not read2 is None: 
UnboundLocalError: local variable 'read1' referenced before assignment

**Comment by Na-He** [comment]
Have you sorted the bam file by read name before using Fast-NR?

**Comment by Na-He** [comment]
> Hi - I receive the following error when running Fast-NR. Could you recommend some actions for troubleshooting. Thanks! Fast-NR -t x.bam -c y.bam -g hg19.chrom.sizes -o 285vs288_FAST_NR.txt -p 1.00e-05 -ws 600 -cp Bonferroni -cm Cosine -ct 2.50e-01 -l 0 -rm False. Step 1: Read in input files. Read in chromosome size file. Read in control file. Traceback (most recent call last): File "/usr/local/bin/Fast-NR", line 8, in sys.exit(main()) File "/usr/local/lib/python2.7/site-packages/src/FastNR.py", line 42, in main control=controlPro.Genome_Frag_all_pos(chrSizeList) File "/usr/local/lib/python2.7/site-packages/src/FastNR.py", line 363, in Genome_Frag_all_pos if not read1 is None and not read2 is None: UnboundLocalError: local variable 'read1' referenced before assignment

Have you sorted the bam files by read name before using Fast-NR

**Comment by cigarsam** [comment]
Thanks for the suggestion. I sorted both files : 
samtools sort x.bam > s_x.bam

This sadly does not resolve the issue. It still gives the same "referenced before assignment" error.

**Comment by cigarsam** [comment]
Thanks for the suggestion. 

I have sorted with the -n flag, but now it gives an error regarding the bam index. 
[E::hts_idx_load3] Could not load local index file 'sname_ABBW284285286merge_nsort_noM.bam.bai'

The index cannot be made with -n read name sorted .bam files, according to both samtools and sambamba.

Thanks!

**Comment by Na-He** [comment]
Please use "samtools sort -n" command try again. If this doesn't solve the problem you can give me part of bam file, so I can try in my compute to check what's the problem.&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Fri, Jun 17, 2022 10:45 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [Na-He/Fast-NR] Error (Issue #1)

&nbsp;



 
Thanks for the suggestion. I sorted both files :
 samtools sort x.bam &gt; s_x.bam
 
This sadly does not resolve the issue. It still gives the same "referenced before assignment" error.
